# Generated by Django 3.2.5 on 2023-02-04 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=7000)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
